FROM node:10.16.0-alpine
WORKDIR /app
COPY . .
EXPOSE 8000
ENV FRONT_URL=http://localhost
RUN npm install && \ 
    adduser -D app && \
    chown -hR app /app
USER app
CMD FRONT_URL=$FRONT_URL npm start
