version: '3.5'

services:
  backend:
      image: backend2.5
      build: ./backend-example-docker
      container_name: back2.5
      ports: 
        - 8000:8000 
      environment: 
        - REDIS=redis 
  frontend:
      image: frontend2.5
      build: ./frontend-example-docker
      container_name: front2.5
      ports: 
        - 5000:5000
  redis:
      image: "redis:alpine"
      container_name: redis

