version: '3.5'

services:
  backend:
    image: backend2.7
    build: ./ml-kurkkumopo-backend
    container_name: back2.7
    ports: 
      - 5000:5000 
    volumes:
      - model:/src/model
  frontend:
    image: frontend2.7
    build: ./ml-kurkkumopo-frontend
    container_name: front2.7
    ports: 
      - 3000:3000
  training:
    image: training2.7
    build: ./ml-kurkkumopo-training
    container_name: tr2.7
    volumes:
      - model:/src/model
      - images:/src/imgs
      - data:/src/data

volumes:
  model:
  images:
  data:

